name: LeftCorlAllegroHandHora
defaults:
  - RightCorlAllegroHandHora
env:
  grasp_cache_name: 'allegro_corl_left'
  reward:
    rotationAxis: [0, 0, 1]
  asset:
     handAsset: 'assets/allegro/allegro_corl_left.urdf'
