name: LeftAllegroHandHora
defaults:
  - RightCorlAllegroHandHora
env:
  reset_height_threshold: 0.625
  grasp_cache_name: 'allegro_left'

  reward:
    rotateRewardScale: 1.25
    rotationAxis: [0, 0, 1]

  asset:
     handAsset: 'assets/allegro/allegro_left.urdf'
