name: RightAllegroHandHora
defaults:
  - AllegroHandHora
env:
  reset_height_threshold: 0.625
  grasp_cache_name: 'allegro_right'

  reward:
    rotateRewardScale: 1.25

  asset:
     handAsset: 'assets/allegro/allegro_right.urdf'
